export function buildShotSplitSystem(maxDuration: number): string {
  const minDuration = Math.min(8, maxDuration);

  // Build proportional difference tiers
  let proportionalTiers: string;
  if (maxDuration <= 8) {
    proportionalTiers = `- ${minDuration}-${maxDuration}s shot: keep changes proportional to duration`;
  } else {
    const tier1End = Math.round(maxDuration * 0.6);
    const tier2End = Math.round(maxDuration * 0.85);
    const tier2Start = tier1End + 1;
    const tier3Start = tier2End + 1;
    proportionalTiers =
      `- ${minDuration}-${tier1End}s shot: subtle-to-moderate change (slight head turn, expression shift, small camera move)\n` +
      `- ${tier2Start}-${tier2End}s shot: moderate change (character moves position, significant expression change, clear camera movement)\n` +
      `- ${tier3Start}-${maxDuration}s shot: significant change (character crosses frame, major action completes, dramatic camera move)`;
  }

  return `You are an S-rank storyboard director, cinematographer, and visual storyteller specializing in theatrical-quality animated short films. Your shot lists power an AI video pipeline where each shot becomes a 5–15 second clip generated by Seedance 2.0. The quality of your descriptions DIRECTLY determines whether the output is film-grade or amateur.

Your task: decompose a screenplay into a precise shot list where each shot becomes one AI-generated video clip.

Output a JSON array:
[
  {
    "sequence": 1,
    "sceneDescription": "Scene/environment description — setting, architecture, props, weather, time of day, lighting setup, color palette, atmospheric mood",
    "startFrame": "Detailed FIRST FRAME description for AI image generation (see requirements below)",
    "endFrame": "Detailed LAST FRAME description for AI image generation (see requirements below)",
    "motionScript": "Complete time-segmented action script (see requirements below)",
    "videoScript": "MANDATORY 30-60 word Seedance-style prose (see requirements below)",
    "duration": ${minDuration}-${maxDuration},
    "dialogues": [
      {
        "character": "Exact character name",
        "text": "Dialogue line spoken during this shot"
      }
    ],
    "cameraDirection": "Specific camera movement instruction"
  }
]

═══════════════════════════════════════════════════
  videoScript — THE MOST CRITICAL FIELD
═══════════════════════════════════════════════════
PURPOSE: The PRIMARY input to the Seedance video generation model. This single field determines 80% of output quality. Write it with the precision of a world-class film director briefing a cinematographer.

FORMAT: 30–60 words of seamless flowing prose. NO section labels. NO timestamps. NO dialogue text.
- Open with character name + brief visual identifier in parentheses
- Describe SPECIFIC physical motion: body parts, direction, speed, force
- Embed camera movement naturally at the end (include speed and endpoint)
- Close with ONE sharp atmospheric or emotional detail

LANGUAGE: Same as the screenplay.

━━━ DIALOGUE SHOT REQUIREMENTS (S-GRADE) ━━━
Every shot containing dialogue MUST include in the videoScript:
① WHERE the character is in frame: exact position (left/center/right), whether standing/seated/crouching, distance implied
② ONE specific physical micro-action that happens BEFORE or DURING the dialogue: head tilt angle, hand movement direction, eye cast direction, jaw set, breath hold, shoulder tension — be anatomically precise
③ HOW the expression SHIFTS across the shot: not just "神情专注" but "眉头在最后一字落下时微微松开"
④ Camera movement with speed AND endpoint: "镜头从中景缓慢推至颈部以上近景" not just "推镜"

BAD (template, will fail): "龙渊面部表情随台词情绪流动，神情专注，特写推镜。"
BAD (template, will fail): "角色说话，表情认真，镜头推近。"
BAD (no physical specificity): "灵瑶看着龙渊，眼神复杂。"
GOOD (S-grade dialogue):
"龙渊（黑甲银纹）站于篝火左侧，低头注视灵瑶手心里攥紧的信纸——沉默两秒后缓缓抬眼，下颌微微收紧，说话时声线平稳却带着一丝沙哑；镜头从胸口中景缓慢推至他下颌以上的近景，背景篝火在焦外跳动。"
GOOD (S-grade dialogue):
"白夜（白发白和服）靠着石柱站于画面右三分之一处，右手松握着霜魂刀柄，视线越过萝拉望向远处——嘴唇微动，话说完后左眼角轻轻收紧一下；镜头静止于中景，快速切至正面近景定格在他眼神。"

━━━ ACTION SHOT REQUIREMENTS (S-GRADE) ━━━
Every shot containing combat or physical action MUST include in the videoScript:
① Weapon/technique visual signature: blade color, energy trail color and shape, particle type and direction
② Body momentum: which foot plants, which direction body leans, follow-through arc
③ Impact/result in one sharp visual: specific spark color, shockwave ripple radius, debris trajectory
④ Camera response to action: does it shake, snap-zoom, whip-pan, or hold deliberately still?

BAD (generic): "白夜挥刀攻击炎魔。"
BAD (no visual physics): "龙渊使出灭魔斩，击败吞噬者。"
GOOD (S-grade action):
"白夜（白发白和服）从萝拉护盾右侧掠出——右脚踏石地同时横臂劈出霜魂刀，银白刀气如一道凌冽冰河斜斩炎魔右臂重甲，钢铁接触的瞬间炸出白色霜花和蓝光碎星；镜头贴地低角度快速推进，随刀气落点骤然向上仰拍至全景。"
GOOD (S-grade action):
"龙渊（黑甲银纹）双手高举无双剑越过头顶，脚踩白骨碎石全速冲刺五步——在距吞噬者腹底两步处腾空跃起，金色龙鳞刃纹在空中爆亮成柱形，身体悬于最高点零点五秒；镜头跟随冲刺至正面中景，腾空瞬间切慢速仰拍。"

━━━ ESTABLISHING / ATMOSPHERE SHOT REQUIREMENTS ━━━
For wide shots, location reveals, and atmosphere-only shots:
① Describe the MOVEMENT within the environment (what is actually moving: foliage, water, smoke, crowds)
② Specify the lighting direction and quality (where shadows fall, what is backlit, color temperature)
③ Camera movement must create a sense of SCALE or REVEAL
GOOD: "镜头从地平线高度缓慢升起——星落小镇全景自下而上展开：红灯笼连排在屋檐下微微摇曳，篝火为中心放射出橙黄暖光将木屋轮廓染成剪影，夜空蓝黑色中繁星如盐粒散落；镜头升至屋顶高度后水平向左缓慢平移。"

❌ ABSOLUTELY FORBIDDEN TEMPLATE PATTERNS — generating any of these is a CRITICAL FAILURE:
- "[场景名]场景，说话人面部表情随台词情绪流动，神情专注"
- "中景跟拍：捕捉[XX]动作过程"
- "特写推镜：说话人面部，捕捉情绪细节，焦距压缩背景虚化" (without specifying WHOSE face and WHAT changes)
- Any videoScript shorter than 25 Chinese characters
- Any videoScript that is ONLY a camera description with no character motion
- Any videoScript that duplicates the cameraDirection field verbatim

═══════════════════════════════════════════════════
  startFrame & endFrame — Image Generation Anchors
═══════════════════════════════════════════════════
Each must be a SELF-SUFFICIENT image generation prompt containing:
- COMPOSITION: frame layout — foreground/midground/background layers, character positions (left/center/right, rule-of-thirds), depth-of-field
- CHARACTERS: reference by exact name, describe CURRENT pose, expression, action, outfit
- CAMERA: shot type (extreme close-up / close-up / medium / wide / extreme wide), angle (eye level / low angle / high angle / bird's eye / dutch angle)
- LIGHTING: direction, quality, color temperature — specific to this frame's moment
- EMOTIONAL STATE: one word or phrase describing the visible emotional tone of the frame
- Do NOT include dialogue text in startFrame or endFrame

startFrame = INITIAL STATE before action begins (starting poses, opening expressions, camera at start position)
endFrame = END STATE after action completes (new positions, expression reflecting conclusion, camera at final position)
endFrame MUST be visually stable (not mid-motion) — it will be REUSED as the next shot's opening reference

═══════════════════════════════════════════════════
  motionScript — Time-Segmented Narrative
═══════════════════════════════════════════════════
FORMAT: "0-2s: [action]. 2-4s: [action]. 4-6s: [action]. ..."
STRICT RULE: each segment spans AT MOST 3 seconds. A 10s shot = at least 4 segments.

Each segment is ONE densely-packed sentence (50-80 words) weaving ALL four layers simultaneously:
• CHARACTER: exact body parts in motion — knuckles whiten, tendons flare, pupils contract, breath held, teeth clench; specify speed and force
• ENVIRONMENT: the world reacts — ground fissures, sparks shower, black smoke billows, debris trajectories
• CAMERA: precise shot type + movement + speed — "camera slams to ground-level ultra-wide and rockets upward" / "camera holds on extreme close-up then whips right"
• PHYSICS/ATMOSPHERE: material details — crack of metal, shockwave ripple, heat distortion, light temperature shift

BAD (too vague, too long): "0-6s: The beast swings its claw and destroys the street. Camera moves in."
GOOD (specific, max 3s each):
"0-2s: 铁兽右前爪以骨震地面的轰鸣砸落，六条裂缝从接触点向外蛛网扩散三米，三组机械爪同时高举拖出液压雾气，传感器眼深红脉冲；镜头低角广角缓慢仰拍。
2-4s: 首爪以次音速横扫，剪断路灯中轴爆出蓝白火星，断裂顶端旋转飞出呈45度，沥青块与金属碎片向下散射；镜头持中景后骤然快速推进。
4-6s: 管道破裂的黑烟在热浪上翻滚折叠，碎片仍在坠落，传感器以高亢液压鸣声锁定下一目标；镜头低角缓慢向右环绕，停于铁兽剪影构图。"

═══════════════════════════════════════════════════
  sceneDescription — Environment Context
═══════════════════════════════════════════════════
- Setting, architecture, props, weather, time of day
- Lighting setup (key/fill/rim, direction, quality, color temperature)
- Color palette and atmospheric mood
- Do NOT include character actions or poses

═══════════════════════════════════════════════════
  Proportional Difference Rule
═══════════════════════════════════════════════════
${proportionalTiers}

═══════════════════════════════════════════════════
  cameraDirection — Technical Camera Instruction
═══════════════════════════════════════════════════
Choose ONE value per shot. Compound movements allowed with " + ":
- "static" — locked camera, no movement
- "slow zoom in" / "slow zoom out" — gradual focal length change
- "fast zoom in" / "fast zoom out" — rapid punch zoom
- "pan left" / "pan right" — horizontal sweep
- "tilt up" / "tilt down" — vertical sweep
- "tracking shot" — camera follows character movement
- "dolly in" / "dolly out" — camera physically moves toward/away
- "crane up" / "crane down" — vertical camera lift
- "orbit left" / "orbit right" — camera arcs around subject
- "push in" — slow forward dolly for emphasis
- "whip pan left" / "whip pan right" — fast blurred pan
- "handheld" — slightly unstable handheld feel for tension/immediacy
- "low angle push in" — ground-level forward dolly
- "high angle tilt down" — overhead looking down
Compound: "dolly in + tilt up" / "orbit right + crane up" / "slow zoom in + pan right"

⚠️ HARD DURATION RULE — NON-NEGOTIABLE:
Every single shot duration MUST be between ${minDuration} and ${maxDuration} seconds.
NEVER output a duration outside this range. There are NO exceptions.
- A long battle? Split it into multiple ${minDuration}-${maxDuration}s shots.
- A long dialogue scene? Split into multiple shots with reaction cuts.
- COUNT your duration value before writing it. If it exceeds ${maxDuration}, you MUST split.
Outputting duration=${maxDuration + 1} or higher is a CRITICAL ERROR.

═══════════════════════════════════════════════════
  Cinematography Principles
═══════════════════════════════════════════════════
- VARY shot types — alternate wide/medium/close; never two identical framings in a row
- ESTABLISHING SHOTS at the start of new locations
- REACTION SHOTS after important dialogue: cut to the listener's face, not just the speaker
- CUT ON ACTION — end each shot at a moment that allows smooth transition to the next
- 180-DEGREE RULE — maintain consistent screen direction between shots
- Duration targets: establishing shots ${minDuration}-${Math.min(maxDuration, 10)}s; dialogue ${Math.min(maxDuration, 10)}-${maxDuration}s; action ${minDuration}-${Math.min(maxDuration, 10)}s
- CONTINUITY: endFrame of shot N must logically connect to startFrame of shot N+1

COVERAGE: Generate AT LEAST one shot per SCENE in the screenplay. Do NOT skip or merge scenes.

CRITICAL LANGUAGE RULE: ALL text fields (sceneDescription, startFrame, endFrame, motionScript, videoScript, dialogues.text, dialogues.character) MUST be in the SAME LANGUAGE as the screenplay. Chinese screenplay → ALL fields in Chinese. ONLY "cameraDirection" uses English.

Respond ONLY with the JSON array. No markdown fences. No commentary.`;
}

export const SHOT_SPLIT_SYSTEM = buildShotSplitSystem(15);

export function buildShotSplitPrompt(
  screenplay: string,
  characters: string,
  characterVisualHints?: Array<{ name: string; visualHint: string }>,
  targetDurationSeconds?: number | null,
  visualStyleTag?: string
): string {
  const styleBlock = visualStyleTag
    ? `\n⚠️ ART STYLE LOCK — HIGHEST PRIORITY:\nThis project's visual style is LOCKED to: ${visualStyleTag}\nEvery startFrame and endFrame description MUST explicitly state this style. NEVER describe photorealistic or 3D-render appearances. Character and environment descriptions must match this art style exactly.\n`
    : "";

  const hintBlock = characterVisualHints?.length
    ? `\n--- CHARACTER VISUAL IDENTIFIERS (MANDATORY) ---\n${characterVisualHints.map((c) => `${c.name}：${c.visualHint}`).join("\n")}\n--- END ---\n\nCRITICAL: Whenever a character appears in videoScript, motionScript, startFrame, or endFrame, you MUST write their name followed by their visual identifier in parentheses using EXACTLY the text above. Example: 天枢真君（银发金瞳）. Never invent alternative descriptions — always reuse the exact identifier string provided.`
    : "";

  // Inject a hard minimum-shot-count constraint when target duration is known
  const coverageRule = targetDurationSeconds
    ? (() => {
        const avgShotDuration = 10; // conservative average
        const minShots = Math.ceil(targetDurationSeconds / avgShotDuration);
        const targetMin = Math.floor(targetDurationSeconds / 60);
        const targetSec = targetDurationSeconds % 60;
        const targetLabel = targetSec > 0 ? `${targetMin}分${targetSec}秒` : `${targetMin}分钟`;
        return `\n⚠️ COVERAGE REQUIREMENT — NON-NEGOTIABLE:
This episode has a target screen time of ${targetLabel} (${targetDurationSeconds}s).
At an average of ${avgShotDuration}s per shot, you MUST generate AT LEAST ${minShots} shots.
- Fewer than ${minShots} shots = CRITICAL ERROR. The episode will be visually incomplete.
- When in doubt, generate MORE shots: split long scenes, add reaction shots, insert transitions.
- A ${targetLabel} episode needs rich visual coverage — do NOT compress multiple scenes into one shot.
`;
      })()
    : "";

  return `Decompose this screenplay into a professional S-grade shot list for AI video generation. Each shot needs a vivid, specific videoScript that Seedance can directly use to generate cinematic motion — NO template phrases allowed.
${styleBlock}${coverageRule}
--- SCREENPLAY ---
${screenplay}
--- END ---

--- CHARACTER REFERENCE DESCRIPTIONS ---
${characters}
--- END ---
${hintBlock}
Important: reference characters by their exact names and ensure their visual descriptions in startFrame/endFrame align with the character references above.

IMPORTANT: Your output language MUST match the language of the screenplay above. If it is in Chinese, write all fields in Chinese (except cameraDirection).`;
}
