import { generateText } from "ai";
import { createLanguageModel } from "@/lib/ai/ai-sdk";
import type { ProviderConfig } from "@/lib/ai/ai-sdk";
import { resolveSlotContents } from "@/lib/ai/prompts/resolver";
import { getPromptDefinition } from "@/lib/ai/prompts/registry";
import { db } from "@/lib/db";
import { characterAssets } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import fs from "node:fs";

export type CharacterAssets = {
  id: string;
  name: string;
};

/**
 * Semantic equivalence map: states that cover each other.
 * If the selected tag covers the "missing" state, suppress the warning.
 */
const STATE_EQUIV: Record<string, string[]> = {
  "武装": ["战斗", "战斗/Combat", "Combat", "Armed", "战斗状态"],
  "战斗": ["武装", "武装状态", "Armed", "武装/战斗"],
  "日常": ["Casual", "Normal", "日常状态"],
  "Casual": ["日常", "Normal"],
  "Combat": ["战斗", "武装", "战斗/Combat"],
  "Armed":  ["武装", "战斗", "武装状态"],
};

function isCoveredByTag(selectedTag: string, missingState: string): boolean {
  const covered = STATE_EQUIV[selectedTag] ?? [];
  return covered.some(s => missingState.toLowerCase().includes(s.toLowerCase()) ||
                           s.toLowerCase().includes(missingState.toLowerCase()));
}

/**
 * Intelligent Agentic Router that determines whether a character is in combat or casual state
 * based on the scene description.
 * It only invokes the LLM if the character has BOTH combat and beauty images to save time/cost.
 */
export async function determineCharacterState(
  sceneDesc: string,
  characterName: string,
  availableTags: string[],
  textModelConfig: ProviderConfig | null | undefined,
  userId: string,
  projectId: string
): Promise<{ tag: string; missing?: string }> {
  if (!textModelConfig || availableTags.length === 0) {
    return { tag: availableTags[0] || "日常" };
  }

  try {
    const model = createLanguageModel(textModelConfig);
    
    const promptKey = "character_state_router";
    const slotContents = await resolveSlotContents(promptKey, { userId, projectId });
    const def = getPromptDefinition(promptKey);
    
    if (!def) throw new Error("character_state_router definition not found");
    
    const fullPrompt = def.buildFullPrompt(slotContents, { 
      characterName, 
      sceneDesc,
      tags: availableTags
    });

    const result = await generateText({
      model,
      prompt: fullPrompt,
    });

    const output = result.text.trim();
    // Parse format: "Match: [Tag] (Missing: [Needed Tag])"
    const matchMatch = output.match(/Match:\s*([^(\n\r]+)/);
    const missingMatch = output.match(/\(Missing:\s*([^)]+)\)/);
    
    let matchedTag = matchMatch ? matchMatch[1].trim() : availableTags[0];
    
    // Ensure the matched tag is actually in the available list
    if (!availableTags.includes(matchedTag)) {
        matchedTag = availableTags[0];
    }

    return { 
        tag: matchedTag,
        missing: missingMatch ? missingMatch[1].trim() : undefined
    };
  } catch (err) {
    console.error(`[CharacterRouter] Failed to determine state for ${characterName}:`, err);
    return { tag: availableTags[0] || "日常" };
  }
}

/**
 * Resolves the most appropriate reference image for each character in a scene.
 * Also returns angle variant images (3q / profile / back) generated by expand_character_asset.
 */
export async function resolveCharacterImages(
  sceneDesc: string,
  characters: CharacterAssets[],
  textModelConfig: ProviderConfig | null | undefined,
  userId: string,
  projectId: string
): Promise<{ name: string; imagePath: string; missingState?: string; angleImagePaths: string[] }[]> {
  const resolved: { name: string; imagePath: string; missingState?: string; angleImagePaths: string[] }[] = [];

  for (const c of characters) {
    // 1. Fetch all morph assets for this character
    const assets = await db.select()
        .from(characterAssets)
        .where(and(
            eq(characterAssets.characterId, c.id),
            eq(characterAssets.assetType, "morph")
        ));

    // Primary assets only (angle = null, i.e., original user-uploaded images)
    const primaryAssets = assets.filter(a => a.angle === null || a.angle === undefined);
    // Angle variant assets (3q / profile / back)
    const angleAssets = assets.filter(a => a.angle !== null && a.angle !== undefined);

    const blueprintAssets = await db.select()
        .from(characterAssets)
        .where(and(
            eq(characterAssets.characterId, c.id),
            eq(characterAssets.assetType, "blueprint")
        ));

    const tags = primaryAssets.map(a => a.tag);
    let finalPath: string | null = null;
    let missing: string | undefined = undefined;
    let selectedTag: string | null = null;

    if (tags.length > 1) {
      // Multiple options -> Ask AI
      const result = await determineCharacterState(sceneDesc, c.name, tags, textModelConfig, userId, projectId);
      const matchedAsset = primaryAssets.find(a => a.tag === result.tag);
      finalPath = matchedAsset?.imagePath || primaryAssets[0]?.imagePath || null;
      selectedTag = result.tag;
      missing = result.missing;
    } else if (tags.length === 1) {
      // Only one morph -> Use it
      finalPath = primaryAssets[0].imagePath;
      selectedTag = primaryAssets[0].tag;
    } else {
      // No morphs -> Use blueprint
      finalPath = blueprintAssets[0]?.imagePath || null;
    }

    if (finalPath) {
      // Suppress missing-state warning if the selected tag semantically covers the needed state
      const effectiveMissing = missing && !isCoveredByTag(tags[0] ?? "", missing) ? missing : undefined;

      // 收集选定服装状态的角度变体图（file 存在才收录）
      const angleImagePaths: string[] = [];
      for (const av of angleAssets) {
        if (av.tag === selectedTag && av.imagePath && fs.existsSync(av.imagePath)) {
          angleImagePaths.push(av.imagePath);
        }
      }

      resolved.push({
        name: c.name,
        imagePath: finalPath,
        missingState: effectiveMissing,
        angleImagePaths,
      });
      if (effectiveMissing) {
          console.warn(`[CharacterRouter] Character "${c.name}" is missing visual state: ${effectiveMissing} in scene: ${sceneDesc}`);
      }
    }
  }

  return resolved;
}
